//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveServerSecondInst.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> ServerId { get; set; }
        public string Condition { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }
        public Nullable<int> PercentageStatus { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> ElementsCalculated { get; set; }
    }
}
